# Generated by Django 3.2.19 on 2023-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20230611_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemwishlist',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='itemwishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemwishlist',
            name='wished_item',
        ),
        migrations.AddField(
            model_name='itemwishlist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itemwishlist',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemwishlist',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
    ]
