# Generated by Django 3.2.19 on 2023-06-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20230611_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wished_item',
            new_name='products',
        ),
    ]
