# Generated by Django 3.2.19 on 2023-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_rename_wished_item_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='sale_alert',
            field=models.BooleanField(default=False),
        ),
    ]
