# Generated by Django 3.2.19 on 2023-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_alter_wishlist_sale_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='sale_alert',
            field=models.BooleanField(),
        ),
    ]
