# Generated by Django 3.2.19 on 2023-06-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_rating'),
        ('wishlist', '0010_auto_20230621_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
        migrations.CreateModel(
            name='WishListSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist')),
            ],
        ),
    ]
