# Generated by Django 3.2.19 on 2023-06-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_auto_20230622_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishListSaleItem',
        ),
    ]
