# Generated by Django 3.2.19 on 2023-06-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0012_delete_wishlistsaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='sale_alert_consent',
            field=models.BooleanField(default=False),
        ),
    ]
