# Generated by Django 3.2.19 on 2023-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_commission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='dominant_colours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
