# Generated by Django 3.2.19 on 2023-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20230623_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='artist',
            field=models.CharField(blank=True, default='None Chosen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='dimensions',
            field=models.CharField(blank=True, default='None Chosen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='dominant_colours',
            field=models.CharField(blank=True, default='None Chosen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='medium',
            field=models.CharField(blank=True, default='None Chosen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.TextField(blank=True, default='We looking at your request and will update you soon!', null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='style',
            field=models.CharField(blank=True, default='None Chosen', max_length=50, null=True),
        ),
    ]
