# Generated by Django 3.2.19 on 2023-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20230623_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.TextField(blank=True, default='We are looking at your request and will update you soon!', null=True),
        ),
    ]
