# Generated by Django 3.2.19 on 2023-06-29 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_commission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='commission',
            name='height_in_mm',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1189)]),
        ),
        migrations.AddField(
            model_name='commission',
            name='width_in_mm',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1189)]),
        ),
    ]
