# Generated by Django 3.2.19 on 2023-06-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20230629_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='dominant_colours',
        ),
    ]
