# Generated by Django 3.2.19 on 2023-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_artist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
