# Generated by Django 3.2.19 on 2023-06-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230621_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_start',
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
