# Generated by Django 3.2.19 on 2023-06-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
    ]
