# Generated by Django 3.2.19 on 2023-06-21 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(0)]),
        ),
    ]
