# Generated by Django 3.2.19 on 2023-06-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230610_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
