# Generated by Django 3.2.19 on 2023-06-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_on_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_percentage',
        ),
    ]
