# Generated by Django 3.2.19 on 2023-06-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_discount_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
