# Generated by Django 3.2.19 on 2023-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(null=True),
        ),
    ]
